// TOEIC Reading Hub β — Part 7 Reading 問題データ
// 共通スキーマ + Part 7 追加項目:
// {
//   id: "TOEIC-2026-0001",
//   part: "Part 7 Reading",
//   level: "easy" | "medium" | "hard",
//   passageType: "email" | "notice" | "article" | "chat" | "advertisement" など,
//   passage: "オリジナル英文パッセージ本文",
//   question: "設問文",
//   options: ["A", "B", "C", "D"],
//   correct: 0,            // 0〜3
//   explanation: "日本語の解説",
//   translation: "パッセージ/設問の和訳",
//   skill: "概要把握 / 詳細 / 推測 / 言い換え など",
//   source: "オリジナル問題",
//   verified: false
// }
// すべてオリジナル英文・オリジナル設問。公式問題・既存教材のコピー禁止。
const QUESTIONS_P7 = [
  {
    id: "TOEIC-2026-0007",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "email",
    passage: "To: All Staff\nFrom: Facilities Management\nSubject: Parking Lot Maintenance\n\nPlease be aware that the north parking lot will be closed for resurfacing from Monday, June 9 to Wednesday, June 11. During this period, employees may use the south lot or the street-level spaces behind Building C. We apologize for any inconvenience and appreciate your cooperation.",
    question: "What are employees asked to do during the maintenance period?",
    options: ["Work from home for three days", "Park in alternative locations", "Pay for street parking", "Report to Building C for reassignment"],
    correct: 1,
    explanation: "本文に「南駐車場やC棟裏の路上スペースを利用してよい」とあり、従業員は代替の場所に駐車するよう求められている。(A) 在宅勤務、(C) 有料駐車、(D) C棟での再配置はいずれも本文に根拠がない。",
    translation: "（宛先：全スタッフ／差出人：施設管理／件名：駐車場メンテナンス）北駐車場は6月9日(月)から11日(水)まで舗装工事のため閉鎖されます。その間、従業員は南駐車場かC棟裏の路上スペースを利用できます。ご不便をおかけしますが、ご協力をお願いいたします。",
    skill: "Part 7 詳細把握（指示内容の読み取り）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0008",
    part: "Part 7 Reading",
    level: "hard",
    passageType: "text message chat",
    passage: "Daniel (9:02 a.m.): The client just moved our presentation up to 1 p.m. today. Can the slides be ready by noon?\nMei (9:05 a.m.): The design is done, but I'm still waiting on the final sales figures from Robert.\nDaniel (9:06 a.m.): I'll call him now. If he sends them within the hour, will that work?\nMei (9:08 a.m.): That's cutting it close, but yes — as long as I have them by eleven.",
    question: "What does Mei imply about finishing the slides?",
    options: ["The design still needs major revisions", "She cannot complete them without Robert's data", "The presentation should be postponed", "She has already sent the slides to the client"],
    correct: 1,
    explanation: "Mei は「デザインは完了したが、Robert からの最終売上数字を待っている」「11時までにもらえれば間に合う」と述べており、Robert のデータがなければスライドを完成できないことを示唆している。(A) デザインは完了済み、(C) 延期には触れていない、(D) 送信済みも本文と矛盾する。",
    translation: "（チャット）ダニエル(9:02):クライアントがプレゼンを今日の13時に前倒しした。正午までにスライドを用意できる？／メイ(9:05):デザインは完成したけど、Robertからの最終売上数字をまだ待っている。／ダニエル(9:06):今すぐ彼に電話する。1時間以内に送ってくれれば間に合う？／メイ(9:08):ぎりぎりだけど、11時までにもらえれば大丈夫。",
    skill: "Part 7 推測（含意の読み取り）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0055",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "email",
    passage: "To: Customer Service Team\nFrom: Daniel Pak, Operations Manager\nSubject: New Response Time Goal\n\nStarting next Monday, we will aim to reply to all customer emails within four hours instead of the current eight. I know this is a big change, so we will add two part-time agents during peak hours to help. Please review the updated reply templates before Monday.",
    question: "What is the main purpose of this email?",
    options: ["To announce a new target for replying to customers", "To apologize for slow customer service", "To advertise a part-time job opening", "To cancel the use of reply templates"],
    correct: 0,
    explanation: "冒頭で「来週月曜から顧客メールへの返信を4時間以内を目標にする」と新しい目標を伝えているため(A)が主旨。(B)謝罪や(D)テンプレ廃止ではなく、(C)求人広告でもない（人員追加やテンプレ確認は目標達成のための手段）。",
    translation: "（件名：新しい返信時間目標）来週月曜から、顧客メールへの返信を現在の8時間ではなく4時間以内を目指します。大きな変更なので、繁忙時間帯にパートを2名追加します。月曜までに更新済みの返信テンプレートを確認してください。",
    skill: "目的把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0056",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "email",
    passage: "To: All Department Heads\nFrom: Facilities\nSubject: Office Move Update\n\nThe move to the new building on Oak Street is now scheduled for the weekend of October 18. Each department will receive labeled boxes on October 14. Please make sure all personal items are packed by 5 p.m. on October 17. Computers will be moved by our IT vendor and should not be unplugged by staff.",
    question: "What are staff members asked NOT to do?",
    options: ["Pack their personal items", "Unplug their computers", "Label their own boxes", "Work on the weekend of October 18"],
    correct: 1,
    explanation: "本文末に「コンピュータはIT業者が移動するので、スタッフは電源を抜かないように」とあるため(B)。(A)私物の梱包は求められており、(C)箱はラベル付きで届き、(D)週末勤務の指示はない。",
    translation: "（件名：オフィス移転の最新情報）オーク通りの新ビルへの移転は10月18日の週末に予定されています。各部署には10月14日にラベル付きの箱が届きます。私物は10月17日午後5時までに梱包してください。コンピュータはIT業者が移動するので、スタッフは電源を抜かないでください。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0057",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "email",
    passage: "To: Mr. Alvarez\nFrom: Greenfield Hotel Reservations\nSubject: Booking Confirmation #4821\n\nThank you for choosing Greenfield Hotel. Your reservation is confirmed for two nights, checking in on May 9 and checking out on May 11. Breakfast is included and served from 6:30 to 10:00 a.m. Check-in begins at 3 p.m. If you arrive earlier, we can store your luggage at the front desk.",
    question: "What is included with the reservation?",
    options: ["Airport pickup", "A late checkout", "Breakfast", "A parking space"],
    correct: 2,
    explanation: "「Breakfast is included」と明記されているため(C)。(A)送迎、(B)レイトチェックアウト、(D)駐車場は本文に記載がない。",
    translation: "（予約確認#4821）グリーンフィールドホテルをお選びいただきありがとうございます。5月9日チェックイン、11日チェックアウトの2泊で予約が確定しました。朝食付きで、6:30〜10:00に提供されます。チェックインは午後3時から。早く到着の場合はフロントで荷物をお預かりします。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0058",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "email",
    passage: "To: Workshop Participants\nFrom: Training Office\nSubject: Venue Change\n\nPlease note that tomorrow's data analysis workshop has been moved from Room 201 to the larger Conference Hall B. Because more people signed up than we expected, Room 201 can no longer hold everyone comfortably. The start time and the materials remain the same.",
    question: "Why was the workshop location changed?",
    options: ["Room 201 needs urgent repairs", "The start time was moved earlier", "The materials were updated", "More people registered than expected"],
    correct: 3,
    explanation: "「予想より多くの人が申し込んだため Room 201 では全員を収容しきれない」と理由が述べられているため(D)。(A)修理や(C)資料更新ではなく、(B)開始時間も変わらない（時間と資料は同じと明記）。",
    translation: "（件名：会場変更）明日のデータ分析ワークショップは Room 201 から、より広い Conference Hall B に変更されました。予想より多くの参加申し込みがあり、Room 201 では全員を快適に収容できないためです。開始時間と資料は変わりません。",
    skill: "理由・原因把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0059",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "email",
    passage: "To: Ms. Chen\nFrom: Bright Path Career Center\nSubject: Mock Interview\n\nThank you for signing up for a mock interview. Your session is set for Thursday at 2 p.m. with one of our career advisors. Please bring a printed copy of your resume. We strongly encourage you to arrive a few minutes early so that we can begin on time.",
    question: "The word 'set' in the email is closest in meaning to",
    options: ["scheduled", "placed", "fixed in position", "decorated"],
    correct: 0,
    explanation: "「Your session is set for Thursday at 2 p.m.」の set は「予定されている」の意味なので(A) scheduled。(B)置く、(C)固定する、(D)飾るは文脈に合わない。",
    translation: "（件名：模擬面接）模擬面接にお申し込みいただきありがとうございます。セッションはキャリアアドバイザーと木曜午後2時に予定されています。印刷した履歴書をお持ちください。定刻に始められるよう、数分早めの到着を強くお勧めします。",
    skill: "言い換え・同義表現",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0060",
    part: "Part 7 Reading",
    level: "hard",
    passageType: "email",
    passage: "To: Marketing Team\nFrom: Lena Ford\nSubject: Campaign Numbers\n\nI just looked at the first-week results for our spring campaign. Click rates are about the same as last year, but the number of people who actually completed a purchase has nearly doubled. Whatever the new landing page is doing, it's working. Let's keep it running and talk on Friday about applying the same design elsewhere.",
    question: "What does Lena suggest about the new landing page?",
    options: ["It has lowered the click rate", "It should be used in other campaigns too", "It needs to be replaced before Friday", "It confused many customers"],
    correct: 1,
    explanation: "「同じデザインを他にも応用する件を金曜に話そう」とあり、効果的なランディングページを他でも使う提案だと読み取れるため(B)。(A)クリック率はほぼ同じで低下ではなく、(C)置き換えではなく継続を指示、(D)購入が倍増しており混乱の根拠はない。",
    translation: "（件名：キャンペーン数値）春のキャンペーンの初週の結果を見ました。クリック率は昨年とほぼ同じですが、実際に購入を完了した人数はほぼ倍増しています。新しいランディングページが効いています。このまま続け、金曜に同じデザインを他にも応用する件を話しましょう。",
    skill: "推論",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0061",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "notice",
    passage: "NOTICE — Library Users\n\nThe quiet study area on the third floor will be reserved for group projects every Friday afternoon from 1 to 5 p.m. during the exam period. Students who need silent study space during these hours may use the reading rooms on the first floor. Normal rules apply at all other times.",
    question: "What is the purpose of this notice?",
    options: ["To announce that the library will close early", "To introduce a new membership fee", "To inform users of a temporary change in room use", "To ask students to return overdue books"],
    correct: 2,
    explanation: "試験期間の金曜午後だけ3階をグループ用にし、静かな学習は1階を使うようにという一時的な利用変更の通知なので(C)。(A)早期閉館、(B)会費、(D)延滞本返却は本文にない。",
    translation: "（図書館利用者へのお知らせ）試験期間中、毎週金曜の午後1時〜5時、3階の静かな学習スペースはグループ作業用に確保されます。この時間に静かな学習場所が必要な学生は1階の閲覧室をご利用ください。それ以外の時間は通常通りです。",
    skill: "目的把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0062",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "notice",
    passage: "NOTICE — Building Maintenance\n\nThe main elevator will be out of service on Wednesday for its annual inspection. The service elevator at the rear of the building will remain available for all floors. Please allow extra time for travel between floors that day. The inspection is expected to finish by 4 p.m.",
    question: "What is available during the inspection?",
    options: ["A free shuttle bus", "Extra parking spaces", "The main elevator", "The service elevator at the rear"],
    correct: 3,
    explanation: "「建物裏のサービス用エレベーターは全階で引き続き利用可能」とあるため(D)。(C)メインのエレベーターは点検中で停止、(A)シャトルや(B)駐車は記載がない。",
    translation: "（建物メンテナンスのお知らせ）水曜、年次点検のためメインのエレベーターが停止します。建物裏のサービス用エレベーターは全階で引き続き利用できます。当日は階の移動に余裕を持ってください。点検は午後4時までに終了予定です。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0063",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "notice",
    passage: "NOTICE — Parking Lot B Closure\n\nParking Lot B will be closed this Saturday so that the surface can be repainted with clearer lane markings. Drivers are asked to use Lot A or the street parking on Maple Avenue. The lot will reopen on Sunday morning. We appreciate your patience while we make these improvements.",
    question: "Why will Parking Lot B be closed?",
    options: ["Its surface will be repainted", "It will be turned into a garden", "A concert will be held there", "It is being sold to another company"],
    correct: 0,
    explanation: "「路面をより見やすい車線表示で塗り直すため」と理由が示されているため(A)。(B)庭、(C)コンサート、(D)売却は本文に根拠がない。",
    translation: "（駐車場B閉鎖のお知らせ）今週土曜、路面をより見やすい車線表示で塗り直すため駐車場Bを閉鎖します。A駐車場かメイプル通りの路上駐車をご利用ください。日曜の朝に再開します。改善作業へのご辛抱に感謝します。",
    skill: "理由・原因把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0064",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "notice",
    passage: "NOTICE — Membership Renewal\n\nYour gym membership is due for renewal at the end of this month. To avoid any interruption to your access, please renew online or at the front desk before the 30th. Members who renew early will receive a complimentary fitness assessment with one of our trainers.",
    question: "The word 'complimentary' is closest in meaning to",
    options: ["polite", "free of charge", "available for an extra fee", "limited in time"],
    correct: 1,
    explanation: "「complimentary fitness assessment」は「無料の」評価の意味なので(B)。complimentary は「ほめる」を表す compliment と紛らわしいが、ここでは無料の意。(A)礼儀正しい、(C)追加料金、(D)時間限定は文脈に合わない。",
    translation: "（会員更新のお知らせ）ジム会員の更新が今月末に必要です。利用が中断しないよう、30日までにオンラインかフロントで更新してください。早めに更新した会員には、トレーナーによる無料のフィットネス評価を進呈します。",
    skill: "言い換え・同義表現",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0065",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "notice",
    passage: "NOTICE — Fire Drill\n\nA scheduled fire drill will take place on Thursday at 10 a.m. When you hear the alarm, please stop your work, leave the building through the nearest exit, and gather at the parking lot. Do not use the elevators. A supervisor will confirm that everyone is accounted for before you return.",
    question: "What are people asked to do when they hear the alarm?",
    options: ["Call the front desk immediately", "Continue working until noon", "Leave through the nearest exit", "Take the elevator down to the lobby"],
    correct: 2,
    explanation: "「警報が鳴ったら最寄りの出口から建物を出て駐車場に集合」とあるため(C)。(D)エレベーターは使わないよう明記され、(A)電話や(B)正午まで作業は本文と矛盾する。",
    translation: "（消防訓練のお知らせ）木曜午前10時に予定された消防訓練を行います。警報が鳴ったら作業を止め、最寄りの出口から建物を出て駐車場に集合してください。エレベーターは使わないでください。戻る前に監督者が全員の安全を確認します。",
    skill: "依頼内容把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0066",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "advertisement",
    passage: "Grand Opening — Riverside Bakery!\n\nCome taste our freshly baked breads and pastries, made every morning with locally sourced ingredients. To celebrate our opening week, every customer receives a free coffee with any purchase. Visit us at 12 Mill Street, open daily from 7 a.m. We can't wait to welcome you!",
    question: "What is the main purpose of this advertisement?",
    options: ["To hire new bakers", "To announce a price increase", "To recall a faulty product", "To promote the opening of a new bakery"],
    correct: 3,
    explanation: "新しいベーカリーの開店を知らせ来店を促す広告なので(D)。(A)採用、(B)値上げ、(C)リコールは本文の目的ではない。",
    translation: "（リバーサイド・ベーカリー グランドオープン！）地元産の材料で毎朝焼き上げるパンとペストリーをぜひご賞味ください。開店週を祝し、ご購入のお客様全員にコーヒーを1杯無料で進呈します。ミル通り12番地、毎日午前7時開店。皆様のご来店をお待ちしています。",
    skill: "目的把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0067",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "advertisement",
    passage: "Spring Cleaning Sale — Home Plus!\n\nThis weekend only, save up to 40% on selected kitchen and bathroom items. Members of our rewards program get an additional 10% off at checkout. Online orders over $50 ship free. The sale ends Sunday at midnight. Some items are limited in stock, so shop early for the best selection.",
    question: "What is required to receive the extra 10% discount?",
    options: ["Being a member of the rewards program", "Spending more than $50", "Shopping in the store on Sunday", "Buying a kitchen appliance"],
    correct: 0,
    explanation: "「リワードプログラムの会員は会計時にさらに10%オフ」とあるため(A)。(B)50ドル超は送料無料の条件であり、(C)日曜の来店や(D)キッチン家電の購入は割引条件として述べられていない。",
    translation: "（ホームプラス 春の大掃除セール！）今週末限定、対象のキッチン・バス用品が最大40%オフ。リワード会員は会計時にさらに10%オフ。50ドル超のオンライン注文は送料無料。セールは日曜深夜まで。在庫が限られる商品もあるのでお早めに。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0068",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "advertisement",
    passage: "Now Hiring: Part-Time Sales Associates\n\nSunbeam Electronics is looking for friendly, motivated people to join our weekend team. No prior experience is necessary — we provide full training. Applicants must be available on both Saturdays and Sundays. Apply by sending your resume to our hiring office by June 15.",
    question: "The phrase 'No prior experience is necessary' suggests that",
    options: ["applicants must have worked in sales before", "beginners are welcome to apply", "only current managers may apply", "the job requires a special license"],
    correct: 1,
    explanation: "「事前の経験は不要で、研修を完備している」とあるので、初心者でも応募歓迎という意味になる(B)。(A)経験必須は逆の内容、(C)管理職限定や(D)資格必要も本文と矛盾する。",
    translation: "（アルバイト募集：販売スタッフ）サンビーム・エレクトロニクスでは週末チームに加わる、明るくやる気のある方を募集中。経験は不要で、研修を完備しています。土日両方に勤務できる方が条件。6月15日までに採用窓口へ履歴書を送ってご応募ください。",
    skill: "言い換え・同義表現",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0069",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "advertisement",
    passage: "Learn a New Language — Anywhere!\n\nWith the LinguaGo app, you can practice speaking for just ten minutes a day. Our lessons fit into your busy schedule, whether you're commuting, waiting in line, or relaxing at home. The first month is free, and you can cancel anytime. Download today and start your first lesson in under a minute.",
    question: "For whom is this app most likely intended?",
    options: ["People who have given up on learning languages", "Professional translators only", "People with limited free time", "Children under the age of five"],
    correct: 2,
    explanation: "「1日たった10分」「通勤中や待ち時間に」など、忙しい人でも使える点を強調しているため、自由時間が限られる人が対象だと推測できる(C)。(A)あきらめた人、(B)プロの翻訳者限定、(D)5歳未満は想定読者として根拠がない。",
    translation: "（新しい言語をどこでも学ぼう！）リンガゴー・アプリなら1日たった10分の会話練習が可能。通勤中、列に並ぶ間、自宅でくつろぐ時など、忙しい予定にも組み込めます。最初の1か月は無料で、いつでも解約できます。今すぐダウンロードして1分以内に最初のレッスンを。",
    skill: "推論",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0070",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "advertisement",
    passage: "Join Our Free Webinar: Smart Budgeting for Beginners\n\nLearn simple ways to track your spending and save more each month. The session is held online on June 20 at 6 p.m. Seats are limited, so registration is required. To reserve your spot, click the link below and fill out the short form. A reminder email will be sent the day before.",
    question: "What should interested people do to attend?",
    options: ["Pay a registration fee in advance", "Call the organizer by phone", "Arrive at the office early", "Register using the online form"],
    correct: 3,
    explanation: "「席に限りがあり登録が必要。リンクから短いフォームに記入して席を予約」とあるため(D)。(A)料金は無料、(B)電話、(C)会場来場はオンライン開催のため不要。",
    translation: "（無料ウェビナー：初心者のためのかしこい家計管理）支出を把握し毎月もっと貯めるシンプルな方法を学べます。6月20日午後6時にオンライン開催。席に限りがあるため登録が必要です。下のリンクをクリックして短いフォームに記入し、席を予約してください。前日にリマインドメールを送ります。",
    skill: "依頼内容把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0071",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "chat",
    passage: "Sara (10:12 a.m.): Hi, are the sample products for the trade show ready to ship?\nTom (10:14 a.m.): Almost — the boxes are packed, but I'm still waiting for the shipping labels.\nSara (10:15 a.m.): When do you think they'll go out?\nTom (10:16 a.m.): If the labels arrive this afternoon, I can send everything by tomorrow morning.",
    question: "Why did Sara contact Tom?",
    options: ["To check on the status of a shipment", "To cancel an order", "To ask for a refund", "To reschedule the trade show"],
    correct: 0,
    explanation: "サラは冒頭で「展示会用のサンプル製品は発送準備ができているか」と尋ねており、発送状況の確認が目的(A)。(B)注文取消、(C)返金、(D)展示会の予定変更は会話に出てこない。",
    translation: "（チャット）サラ(10:12):展示会用のサンプル製品は発送準備できてる？／トム(10:14):ほぼね。箱は梱包済みだけど発送ラベル待ち。／サラ(10:15):いつ頃出せそう？／トム(10:16):ラベルが今日の午後に届けば、明日の朝までに全部送れるよ。",
    skill: "目的把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0072",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "chat",
    passage: "Priya (3:40 p.m.): Did the client approve the final design?\nMarco (3:42 p.m.): Not yet. They liked the layout but asked us to change the color scheme.\nPriya (3:43 p.m.): Any particular reason?\nMarco (3:44 p.m.): They felt the blue was too dark and wanted something that matches their new logo.\nPriya (3:45 p.m.): Got it. I'll prepare a few lighter options.",
    question: "Why did the client ask for changes?",
    options: ["The layout was confusing", "The colors did not match their new logo", "The design was submitted late", "The price was too high"],
    correct: 1,
    explanation: "マルコが「青が暗すぎて、新しいロゴに合うものを求めた」と説明しているため(B)。(A)レイアウトは気に入っており、(C)提出の遅れや(D)価格は会話に出てこない。",
    translation: "（チャット）プリヤ(3:40):クライアントは最終デザインを承認した？／マルコ(3:42):まだ。レイアウトは気に入ったけど配色を変えてほしいって。／プリヤ(3:43):何か理由は？／マルコ(3:44):青が暗すぎて、新しいロゴに合うものがいいと。／プリヤ(3:45):了解、明るめの案をいくつか用意する。",
    skill: "理由・原因把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0073",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "chat",
    passage: "Ken (1:05 p.m.): The printer on the second floor is jammed again.\nMia (1:06 p.m.): Ugh, not again. Did you try the one in the copy room?\nKen (1:07 p.m.): Yeah, but it's out of toner.\nMia (1:08 p.m.): Okay, I'll put in a request for both. In the meantime, use the printer near reception.",
    question: "The phrase 'out of toner' means that the printer",
    options: ["is making loud noises", "has been moved to another floor", "has no toner left", "is brand new"],
    correct: 2,
    explanation: "out of toner は「トナーが切れている」状態を表すため(C)。(A)騒音、(B)別の階への移動、(D)新品は文脈に合わない。",
    translation: "（チャット）ケン(1:05):2階のプリンターがまた紙詰まり。／ミア(1:06):またか…。コピー室のは試した？／ケン(1:07):うん、でもトナー切れ。／ミア(1:08):じゃあ両方修理を依頼するね。それまで受付近くのプリンターを使って。",
    skill: "言い換え・同義表現",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0074",
    part: "Part 7 Reading",
    level: "hard",
    passageType: "chat",
    passage: "Jay (9:30 a.m.): Are you joining the budget meeting at 11?\nAmara (9:31 a.m.): I want to, but my train is delayed and I'm still three stops away.\nJay (9:32 a.m.): No worries. I can share my screen and notes with you afterward.\nAmara (9:33 a.m.): That would really help. I'll review them as soon as I get in and send you my comments.",
    question: "What will Amara most likely do?",
    options: ["Cancel the budget meeting", "Get off the train early", "Lead the meeting from home", "Review Jay's notes after she arrives"],
    correct: 3,
    explanation: "アマラは「着いたらすぐ確認してコメントを送る」と述べており、ジェイのメモを到着後に確認すると推測できる(D)。(A)会議の中止、(B)早めの下車、(C)在宅での進行は会話の内容と一致しない。",
    translation: "（チャット）ジェイ(9:30):11時の予算会議に出る？／アマラ(9:31):出たいけど電車が遅れてて、まだ3駅手前。／ジェイ(9:32):大丈夫、後で画面とメモを共有するよ。／アマラ(9:33):助かる。着いたらすぐ確認してコメントを送るね。",
    skill: "推論",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0075",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "article",
    passage: "Local News\n\nThe city has announced a new bike-sharing program that will launch this summer. Twenty stations will be placed near train stops and shopping areas, allowing residents to rent bicycles by the hour. City officials hope the program will reduce traffic and encourage healthier commuting. A mobile app will let users find and unlock bikes easily.",
    question: "What is the article mainly about?",
    options: ["A new bike-sharing program in the city", "A change to the train schedule", "The closing of several shopping areas", "A rise in local fuel prices"],
    correct: 0,
    explanation: "記事は夏に始まる新しい自転車シェアプログラムを中心に紹介しているため(A)。(B)電車の時刻、(C)商業地区の閉鎖、(D)燃料価格は記事の主題ではない。",
    translation: "（地域ニュース）市はこの夏に始まる新しい自転車シェアリングプログラムを発表した。駅や商業エリアの近くに20か所のステーションを設置し、住民は時間単位で自転車を借りられる。市は交通量の削減と健康的な通勤の促進を期待している。専用アプリで自転車を簡単に探して解錠できる。",
    skill: "目的把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0076",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "article",
    passage: "Business Briefs\n\nGreenleaf Cafe has decided to extend its opening hours on weekdays. According to the owner, many customers had asked for an earlier opening so they could grab coffee before work. Starting next week, the cafe will open at 6:30 a.m. instead of 8 a.m. The closing time will remain unchanged.",
    question: "Why did the cafe change its hours?",
    options: ["It hired more staff", "Customers wanted to buy coffee earlier", "A new cafe opened nearby", "Its rent increased"],
    correct: 1,
    explanation: "「多くの客が仕事前にコーヒーを買えるよう早い開店を求めていた」とあるため(B)。(A)増員、(C)近隣の新店、(D)家賃上昇は理由として述べられていない。",
    translation: "（ビジネス短信）グリーンリーフ・カフェは平日の営業時間を延長することにした。オーナーによれば、多くの客が仕事前にコーヒーを買えるよう早い開店を求めていた。来週から開店を午前8時から6時半に変更する。閉店時間は変わらない。",
    skill: "理由・原因把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0077",
    part: "Part 7 Reading",
    level: "hard",
    passageType: "article",
    passage: "Technology Update\n\nA local startup has developed a device that helps reduce water waste in homes. The small sensor attaches to a faucet and alerts users through an app when it detects a leak. Early testers reported that the device paid for itself within a few months by lowering their water bills. The company plans to release it nationwide next year.",
    question: "The phrase 'paid for itself' suggests that the device",
    options: ["was given away for free", "stopped working after a few months", "saved enough money to cover its cost", "was difficult to install"],
    correct: 2,
    explanation: "「数か月で水道代を下げて元が取れた」という文脈で paid for itself は「自身のコストを賄えるだけ節約した」を意味するため(C)。(A)無料配布、(B)故障、(D)設置の難しさは本文と合わない。",
    translation: "（テクノロジー最新情報）ある地元スタートアップが、家庭の水の無駄を減らす装置を開発した。小型センサーを蛇口に取り付け、漏れを検知するとアプリで通知する。初期テスターは、水道代が下がり数か月で元が取れたと報告した。同社は来年の全国発売を計画している。",
    skill: "言い換え・同義表現",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0078",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "article",
    passage: "Community Notice\n\nThe town's annual park cleanup will be held on Saturday morning. Volunteers of all ages are welcome. Gloves and trash bags will be provided, but participants should wear comfortable shoes and bring their own water. Anyone interested should sign up at the community center by Thursday so that organizers can prepare enough supplies.",
    question: "What are interested volunteers asked to do?",
    options: ["Bring their own trash bags", "Pay a small participation fee", "Arrive at the park on Friday", "Sign up by Thursday"],
    correct: 3,
    explanation: "「主催者が十分な備品を準備できるよう木曜までにコミュニティセンターで申し込むように」とあるため(D)。(A)ゴミ袋は提供され、(B)料金や(C)金曜来場は本文と異なる（開催は土曜）。",
    translation: "（地域のお知らせ）町の年次公園清掃が土曜の午前に行われます。年齢を問わずボランティア歓迎。手袋とゴミ袋は用意しますが、参加者は歩きやすい靴を履き、各自の水を持参してください。参加希望者は、主催者が十分な備品を準備できるよう木曜までにコミュニティセンターで申し込んでください。",
    skill: "依頼内容把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0079",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "schedule",
    passage: "Training Schedule — New Employees (Day 1)\n\n9:00 a.m. — Welcome and company overview\n10:30 a.m. — Office tour\n12:00 p.m. — Lunch (provided)\n1:00 p.m. — Software systems training\n3:30 p.m. — Q&A with team leaders\n\nPlease arrive by 8:45 a.m. and bring a photo ID to receive your access badge.",
    question: "What is scheduled right after lunch?",
    options: ["Software systems training", "The office tour", "The company overview", "Q&A with team leaders"],
    correct: 0,
    explanation: "昼食(12:00)の直後、午後1時は「ソフトウェアシステム研修」とあるため(A)。(B)オフィスツアーと(C)会社概要は午前、(D)Q&Aは午後3時半で時間が異なる。",
    translation: "（新入社員 研修スケジュール 1日目）9:00 歓迎と会社概要／10:30 オフィスツアー／12:00 昼食（提供）／13:00 ソフトウェアシステム研修／15:30 チームリーダーとのQ&A。8:45までに到着し、入館バッジ受け取りのため写真付き身分証をお持ちください。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0080",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "memo",
    passage: "MEMO\nTo: All Staff\nFrom: HR Department\nRe: Updated Remote Work Policy\n\nBeginning July 1, employees may work from home up to two days per week. Remote days must be approved by your manager in advance and cannot fall on the same day as a scheduled team meeting. Staff are expected to be reachable by email and messaging during normal working hours.",
    question: "According to the memo, what is NOT allowed?",
    options: ["Working from home twice a week", "Taking a remote day on a team meeting day", "Emailing during working hours", "Asking a manager for approval"],
    correct: 1,
    explanation: "「在宅日はチーム会議の予定日と同じ日にはできない」とあるため(B)が許可されない。(A)週2日までの在宅は可能、(C)勤務時間中のメール対応は求められ、(D)上司の事前承認は必要。",
    translation: "（メモ：在宅勤務ポリシー改定）7月1日より、従業員は週2日まで在宅勤務が可能です。在宅日は上司の事前承認が必要で、チーム会議の予定日と同じ日には設定できません。スタッフは通常の勤務時間中、メールやメッセージで連絡が取れる状態である必要があります。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0081",
    part: "Part 7 Reading",
    level: "hard",
    passageType: "policy",
    passage: "Return Policy\n\nItems may be returned within 30 days of purchase for a full refund, provided they are unused and in their original packaging. Items marked 'final sale' cannot be returned or exchanged. Refunds are issued to the original payment method within five business days. Shipping costs are non-refundable.",
    question: "What can be inferred about a 'final sale' item?",
    options: ["It can be returned within 30 days", "It comes with free shipping", "It cannot be returned even if it is unused", "It is always sold at the highest price"],
    correct: 2,
    explanation: "「final sale 表示の商品は返品も交換もできない」とあるため、未使用であっても返品できないと推測できる(C)。(A)30日以内の返品は通常商品の条件で、(B)送料無料や(D)最高価格での販売は本文に根拠がない。",
    translation: "（返品ポリシー）商品は未使用かつ元の梱包であれば、購入から30日以内に全額返金で返品できます。「final sale（最終セール）」表示の商品は返品・交換できません。返金は5営業日以内に元の支払い方法へ行われます。送料は返金対象外です。",
    skill: "推論",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0082",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "memo",
    passage: "MEMO\nTo: Sales Team\nFrom: Regional Manager\nRe: Monthly Reports\n\nThis is a reminder that monthly sales reports are due on the last business day of each month. Please submit your report through the shared online folder, not by email. If you need help accessing the folder, contact the IT support desk before the deadline.",
    question: "How should team members submit their reports?",
    options: ["By printing and mailing them", "By handing them to the manager in person", "By sending them as an email attachment", "By uploading them to the shared online folder"],
    correct: 3,
    explanation: "「メールではなく共有オンラインフォルダから提出するように」と明記されているため(D)。(C)メール添付は明確に否定されており、(A)郵送や(B)手渡しは本文にない。",
    translation: "（メモ：月次報告について）月次の営業報告は毎月最終営業日が締め切りです。報告はメールではなく共有オンラインフォルダから提出してください。フォルダへのアクセスに困ったら、締め切り前にITサポートデスクへ連絡してください。",
    skill: "依頼内容把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0131",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "email",
    passage: "To: All Team Leads\nFrom: Olivia Grant, HR\nSubject: Quarterly Check-ins\n\nStarting in April, we will hold short one-on-one check-ins between each team lead and their members every quarter. These meetings are meant to discuss goals and any support staff may need. Please schedule your first round before the end of the month.",
    question: "What is the main purpose of the email?",
    options: ["To introduce regular one-on-one meetings","To announce a company-wide layoff","To advertise a training course","To request payment from clients"],
    correct: 0,
    explanation: "「四半期ごとに1対1の面談を始める」と新しい定例面談の導入を伝えているため(A)が主旨。(B)解雇・(C)研修広告・(D)支払い請求は本文に根拠がない。",
    translation: "（件名：四半期面談）4月から、各チームリーダーとメンバーの間で四半期ごとに短い1対1の面談を行います。目標や必要な支援について話し合うためのものです。月末までに第1回を予定してください。",
    skill: "目的把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0132",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "email",
    passage: "To: Mr. Reed\nFrom: Pinecrest Hotel\nSubject: Your Upcoming Stay\n\nWe look forward to welcoming you on March 3. Please note that check-in starts at 3:00 p.m., and our complimentary airport shuttle runs every hour from 6:00 a.m. to 10:00 p.m. Parking is available on-site for a daily fee. Let us know if you need an early check-in.",
    question: "What is offered free of charge?",
    options: ["On-site parking","The airport shuttle","An early check-in","Room service"],
    correct: 1,
    explanation: "「complimentary airport shuttle（無料の空港シャトル）」とあるため(B)。(A)駐車は有料、(C)アーリーチェックインは要相談、(D)ルームサービスは記載がない。",
    translation: "（件名：ご宿泊について）3月3日のお越しをお待ちしています。チェックインは午後3時から、無料の空港シャトルは午前6時〜午後10時まで毎時運行します。敷地内駐車場は1日料金で利用可。アーリーチェックインをご希望の際はお知らせください。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0133",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "email",
    passage: "To: Marketing Team\nFrom: David Lin\nSubject: Brochure Draft\n\nThanks for sending the draft brochure. The layout looks great, but a few product prices are outdated. Could you update them using the latest price list I shared last week? Once that's done, please send the revised version to the printer by Thursday.",
    question: "What does David ask the team to do first?",
    options: ["Design a new layout","Contact the printer directly","Update the product prices","Create a new price list"],
    correct: 2,
    explanation: "「最新の価格表を使って価格を更新してほしい」とまず依頼しているため(C)。(A)レイアウトは良いと評価、(B)印刷会社への送付は更新後、(D)価格表は既に共有済みで新規作成ではない。",
    translation: "（件名：パンフレット案）パンフレット案の送付ありがとう。レイアウトは良いけれど、いくつかの製品価格が古い。先週共有した最新の価格表で更新してくれる？それが終わったら、木曜までに修正版を印刷会社に送って。",
    skill: "依頼内容把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0134",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "email",
    passage: "To: Ms. Park\nFrom: Cloverfield Community Center\nSubject: Class Confirmation\n\nYour spot in the Saturday pottery class has been secured. The course runs for six weeks, and all materials are provided. If you are unable to attend a session, please let us know in advance so we can offer your place to someone on the waiting list.",
    question: "The word 'secured' is closest in meaning to",
    options: ["paid","decorated","limited","reserved"],
    correct: 3,
    explanation: "「Your spot … has been secured」の secured は「確保された＝予約された」の意味なので(D) reserved。(A)支払われた・(B)飾られた・(C)制限されたは文脈に合わない。",
    translation: "（件名：クラス確認）土曜の陶芸クラスのお席を確保しました。コースは6週間で、材料はすべて提供されます。参加できない回がある場合は、キャンセル待ちの方にお席をご案内できるよう、事前にお知らせください。",
    skill: "言い換え・同義表現",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0135",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "notice",
    passage: "NOTICE — Office Recycling\n\nStarting Monday, new recycling stations will be placed on each floor. Paper, plastic, and cans should be sorted into the labeled bins. The single trash cans near the elevators will be removed to encourage proper sorting. Thank you for helping us reduce waste.",
    question: "Why is this notice being posted?",
    options: ["To explain a new recycling system","To announce a holiday schedule","To report a power outage","To request volunteers for an event"],
    correct: 0,
    explanation: "各階に分別ステーションを設置し正しい分別を促す新システムの案内なので(A)。(B)休日予定・(C)停電・(D)ボランティア募集は本文にない。",
    translation: "（お知らせ：オフィスのリサイクル）月曜から、各階に新しいリサイクルステーションを設置します。紙・プラスチック・缶はラベル付きの箱に分別してください。正しい分別を促すため、エレベーター近くの単一ゴミ箱は撤去します。ごみ削減へのご協力に感謝します。",
    skill: "目的把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0136",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "notice",
    passage: "NOTICE — Gym Renovation\n\nThe fitness center will be closed for renovation from June 1 to June 14. During this period, members can use the partner gym on Elm Street at no extra cost by showing their membership card. Locker rentals will be paused and refunded for the closure period. Normal service resumes June 15.",
    question: "What can members do during the closure?",
    options: ["Receive a full membership refund","Use a partner gym for free","Rent a locker at a discount","Attend online fitness classes"],
    correct: 1,
    explanation: "「会員カードを見せれば追加料金なしで提携ジムを利用できる」とあるため(B)。(A)全額返金はロッカー分のみ、(C)ロッカーは休止、(D)オンライン講座は記載がない。",
    translation: "（お知らせ：ジム改装）フィットネスセンターは6月1日〜14日まで改装で閉鎖します。期間中、会員は会員カードの提示でエルム通りの提携ジムを追加料金なしで利用できます。ロッカー貸出は休止し、閉鎖期間分は返金します。通常営業は6月15日再開。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0137",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "notice",
    passage: "NOTICE — Temporary Water Shutoff\n\nWater service in Building A will be turned off on Wednesday from 10 a.m. to 2 p.m. so that crews can repair a leaking pipe on the third floor. Restrooms in Building B will remain open. We appreciate your patience while we complete this urgent repair.",
    question: "Why will the water be shut off?",
    options: ["To install new sinks","To clean the water tank","To repair a leaking pipe","To test the fire alarm"],
    correct: 2,
    explanation: "「3階の漏れている配管を修理するため」と理由が述べられているため(C)。(A)流し設置・(B)貯水槽清掃・(D)火災報知器点検は本文にない。",
    translation: "（お知らせ：一時断水）水曜午前10時〜午後2時、3階の漏水している配管を修理するためA棟の給水を停止します。B棟のトイレは利用可能です。緊急修理へのご辛抱に感謝します。",
    skill: "理由・原因把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0138",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "advertisement",
    passage: "Now Open — Meadow Lane Co-Working Space!\n\nNeed a quiet place to focus or meet clients? Meadow Lane offers desks, private meeting rooms, and fast Wi-Fi in the heart of downtown. Day passes and monthly plans are available. Stop by this week for a free tour and a complimentary cup of coffee.",
    question: "What is the purpose of this advertisement?",
    options: ["To hire office cleaners","To sell used furniture","To announce a price increase","To promote a new co-working space"],
    correct: 3,
    explanation: "新しいコワーキングスペースの開業を知らせ利用を促す広告なので(D)。(A)清掃員採用・(B)中古家具販売・(C)値上げは本文の目的でない。",
    translation: "（オープン：メドウレーン・コワーキングスペース！）集中したり顧客と会ったりする静かな場所が必要ですか？メドウレーンは中心街にデスク・個室会議室・高速Wi-Fiを提供します。1日券と月額プランあり。今週お立ち寄りで無料見学とコーヒー1杯を進呈。",
    skill: "目的把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0139",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "advertisement",
    passage: "Spring Membership Offer — Riverbend Museum\n\nJoin now and enjoy unlimited entry for a full year, plus a 15% discount at the gift shop and cafe. New members who sign up before April 30 will also receive two guest passes. Memberships can be purchased online or at the front desk. Student rates are available with a valid ID.",
    question: "What do members who join before April 30 receive in addition?",
    options: ["Two guest passes","A free parking permit","A printed catalog","A private guided tour"],
    correct: 0,
    explanation: "「4月30日までに入会する新会員はゲストパス2枚も受け取る」とあるため(A)。(B)駐車許可・(C)カタログ・(D)個別ツアーは記載がない。",
    translation: "（春の会員特典：リバーベンド美術館）今ご入会で1年間の入場無制限に加え、ギフトショップとカフェで15%割引。4月30日までに登録の新会員にはゲストパス2枚も進呈。会員はオンラインか受付で購入可。学生料金は有効な身分証で利用可。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0140",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "advertisement",
    passage: "Tired of long checkout lines? Try our mobile checkout app! Scan items as you shop, pay on your phone, and walk right out. No more waiting at the register. Available at all our supermarket locations. Download today and get $5 off your first order over $30.",
    question: "What problem does the app aim to solve?",
    options: ["High grocery prices","Time spent waiting in line","A shortage of staff","Limited store hours"],
    correct: 1,
    explanation: "「長いレジ待ちにうんざり？」「もうレジで待つ必要はない」と本文に述べられており、列に並ぶ時間の問題を解決する狙いだと分かるため(B)。(A)価格・(C)人手不足・(D)営業時間は本文の主眼でない。",
    translation: "（広告）長いレジ待ちにうんざり？当店のモバイル決済アプリをお試しください。買い物しながら商品をスキャンし、スマホで支払い、そのまま退店できます。もうレジで待つ必要はありません。全店舗で利用可。今すぐダウンロードで、30ドル以上の初回注文が5ドル引き。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0141",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "chat",
    passage: "Nina (2:10 p.m.): Hi, are we still on for the venue visit tomorrow?\nLeo (2:12 p.m.): Yes, but the manager asked if we could come at 11 instead of 10.\nNina (2:13 p.m.): That works for me. Should I bring the floor plan?\nLeo (2:14 p.m.): Please do. It'll help us decide where to set up the stage.",
    question: "Why did Leo message Nina?",
    options: ["To cancel the venue visit","To ask for a refund","To inform her of a time change","To complain about the manager"],
    correct: 2,
    explanation: "レオは「会場の都合で10時ではなく11時に来られるか」と時間変更を伝えているため(C)。(A)中止・(B)返金・(D)苦情は会話にない。",
    translation: "（チャット）ニナ(2:10):明日の会場見学は予定どおり？／レオ(2:12):うん、ただ担当者が10時じゃなく11時に来られるか聞いてる。／ニナ(2:13):大丈夫。間取り図を持っていこうか？／レオ(2:14):お願い。ステージの設置場所を決めるのに役立つよ。",
    skill: "目的把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0142",
    part: "Part 7 Reading",
    level: "hard",
    passageType: "chat",
    passage: "Aiko (4:05 p.m.): Did the samples arrive from the supplier?\nMark (4:07 p.m.): They came, but the color is slightly off from what we approved.\nAiko (4:08 p.m.): How noticeable is it?\nMark (4:09 p.m.): Honestly, most customers probably wouldn't notice, but I don't want to risk it before the launch.\nAiko (4:10 p.m.): Agreed. Let's ask them to redo it.",
    question: "What does Mark imply about the samples?",
    options: ["They arrived later than expected","The color is exactly correct","Customers have already complained","He is not fully satisfied with them"],
    correct: 3,
    explanation: "マークは「色が承認したものとわずかに違う」「発売前に冒険したくない」と述べ、サンプルに完全には満足していないことを示唆しているため(D)。(A)到着遅延・(B)色は正確・(C)顧客の苦情は会話と一致しない。",
    translation: "（チャット）アイコ(4:05):業者からサンプル届いた？／マーク(4:07):届いたけど、承認した色と少し違う。／アイコ(4:08):どれくらい目立つ？／マーク(4:09):正直、ほとんどの客は気づかないと思うけど、発売前に冒険はしたくない。／アイコ(4:10):同感。作り直しを頼もう。",
    skill: "推論",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0143",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "chat",
    passage: "Sam (9:00 a.m.): The client wants to move the deadline up by a week.\nRia (9:02 a.m.): That's tight, but doable if we drop the optional features for now.\nSam (9:03 a.m.): Good idea. Let's focus on the core ones first.\nRia (9:04 a.m.): I'll update the task list and share it with the team.",
    question: "The phrase 'move the deadline up' means to make the deadline",
    options: ["earlier","later","optional","longer"],
    correct: 0,
    explanation: "move the deadline up は「締め切りを前倒しにする＝早める」の意味なので(A) earlier。(B)遅らせる・(C)任意にする・(D)延ばすは誤り。",
    translation: "（チャット）サム(9:00):クライアントが締め切りを1週間前倒ししたいって。／リア(9:02):きついけど、任意機能を今は外せば可能。／サム(9:03):いいね。まず中核機能に集中しよう。／リア(9:04):タスク一覧を更新してチームに共有する。",
    skill: "言い換え・同義表現",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0144",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "article",
    passage: "Community News\n\nThe town library has launched a new program that lends out more than just books. Starting this month, residents can borrow tools, board games, and even musical instruments using their library cards. Organizers hope the 'library of things' will help families save money and try new hobbies without a big upfront cost.",
    question: "What is the article mainly about?",
    options: ["An increase in library fees","A new library lending program","The closing of a local library","A shortage of library books"],
    correct: 1,
    explanation: "図書館が本以外（工具・ボードゲーム・楽器）も貸し出す新プログラムを中心に紹介しているため(B)。(A)料金値上げ・(C)閉館・(D)本不足は記事の主題でない。",
    translation: "（地域ニュース）町の図書館が、本以外も貸し出す新プログラムを始めた。今月から、住民は図書館カードで工具・ボードゲーム・楽器まで借りられる。主催者は、この「ものの図書館」が家族の節約や、初期費用をかけずに新しい趣味を試す助けになることを期待している。",
    skill: "目的把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0145",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "article",
    passage: "Business Notes\n\nLocal bakery Rolling Pin has decided to switch to paper packaging for all its products. The owner explained that many customers had expressed concern about plastic waste. Although paper costs slightly more, the bakery believes the change reflects its values and will appeal to environmentally conscious shoppers.",
    question: "Why did the bakery change its packaging?",
    options: ["Paper was cheaper than plastic","A new law required the change","Customers were concerned about plastic waste","The old packaging was hard to find"],
    correct: 2,
    explanation: "「多くの客がプラスチックごみへの懸念を示していた」と理由が述べられているため(C)。(A)紙の方が高い、(B)法律や(D)入手難は本文にない。",
    translation: "（ビジネスノート）地元のパン店ローリングピンが、全商品を紙包装に切り替えることにした。オーナーは、多くの客がプラスチックごみを心配していたと説明する。紙は少し高いが、店はこの変更が自分たちの価値観を表し、環境意識の高い客に響くと考えている。",
    skill: "理由・原因把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0146",
    part: "Part 7 Reading",
    level: "hard",
    passageType: "article",
    passage: "Technology Trends\n\nA growing number of companies are letting employees set their own working hours. Supporters say this flexibility boosts morale and productivity, as people can work when they feel most focused. Critics, however, warn that without clear boundaries, some workers may find it hard to switch off and end up working longer than before.",
    question: "The phrase 'switch off' is closest in meaning to",
    options: ["turn on the lights","change careers","work overtime","stop working and relax"],
    correct: 3,
    explanation: "ここでの switch off は「仕事から離れて休む・オフにする」の意味なので(D) stop working and relax。(A)照明・(B)転職・(C)残業は文脈に合わない。",
    translation: "（テクノロジー動向）従業員に勤務時間を自分で決めさせる企業が増えている。支持者は、人は最も集中できる時に働けるため、この柔軟性が士気と生産性を高めると言う。一方批判する人は、明確な境界がないと一部の人は仕事から離れにくく、以前より長く働いてしまうおそれがあると警告する。",
    skill: "言い換え・同義表現",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0147",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "memo",
    passage: "MEMO\nTo: All Staff\nFrom: Facilities\nRe: New Visitor Policy\n\nBeginning next Monday, all visitors must sign in at the front desk and wear a visitor badge while in the building. Employees are responsible for escorting their guests at all times. Badges must be returned when visitors leave. This policy is intended to improve building security.",
    question: "What are employees required to do under the new policy?",
    options: ["Escort their visitors at all times","Pay a fee for each guest","Submit visitor names a week early","Park in the visitor lot"],
    correct: 0,
    explanation: "「従業員は常に来訪者に付き添う責任がある」とあるため(A)。(B)料金・(C)1週間前の名前提出・(D)来客用駐車は本文にない。",
    translation: "（メモ：来訪者ポリシー）来週月曜から、すべての来訪者は受付で記帳し、館内では来訪者バッジを着用する必要があります。従業員は常に来客に付き添う責任があります。バッジは退館時に返却。本ポリシーは建物のセキュリティ向上が目的です。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0148",
    part: "Part 7 Reading",
    level: "hard",
    passageType: "policy",
    passage: "Exchange Policy\n\nClothing may be exchanged within 21 days of purchase if the tags are still attached and the items are unworn. Sale items can be exchanged but not refunded. Exchanges can be made at any branch with the original receipt. For online orders, customers must request an exchange label through their account before sending items back.",
    question: "What is required before returning an online purchase?",
    options: ["It cannot be exchanged at all","It requires an exchange label before return","It must be returned within 7 days","It is always a final sale"],
    correct: 1,
    explanation: "「オンライン注文は返送前にアカウントから交換ラベルを請求する必要がある」と本文に明記されているため(B)。(A)交換不可・(C)7日以内・(D)常に最終セールは本文と一致しない。",
    translation: "（交換ポリシー）衣料品はタグが付いたままで未着用なら購入から21日以内に交換可。セール品は交換できるが返金不可。交換は元のレシートがあればどの店舗でも可能。オンライン注文の場合、返送前にアカウントから交換ラベルを請求する必要があります。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0149",
    part: "Part 7 Reading",
    level: "advanced",
    passageType: "review",
    passage: "Customer Review — Northgate Bistro (4 out of 5 stars)\n\nWe came for a birthday dinner and were impressed by the friendly staff and cozy atmosphere. The pasta was excellent, though the dessert menu was a bit limited. One downside was the wait — we had a reservation but were still seated 20 minutes late. Still, we would happily return.",
    question: "What did the reviewer dislike?",
    options: ["The unfriendly staff","The taste of the pasta","Waiting past the reservation time","The high prices"],
    correct: 2,
    explanation: "「予約していたのに20分遅れて案内された」という待ち時間を欠点として挙げているため(C)。(A)スタッフは親切、(B)パスタは絶品、(D)価格は触れていない。",
    translation: "（口コミ：ノースゲート・ビストロ 5つ星中4つ星）誕生日ディナーで訪れ、親切なスタッフと居心地のよい雰囲気に感心しました。パスタは絶品でしたが、デザートの種類は少し限られていました。難点は待ち時間で、予約していたのに案内は20分遅れ。それでも、また喜んで訪れたいです。",
    skill: "詳細把握",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0150",
    part: "Part 7 Reading",
    level: "standard",
    passageType: "web page",
    passage: "Help Center — Resetting Your Password\n\nIf you have forgotten your password, click 'Forgot Password' on the login page and enter the email linked to your account. We will send a reset link, which expires after 30 minutes. If you do not see the email, please check your spam folder. For further help, contact our support team through the live chat.",
    question: "What should users do if they do not receive the reset email?",
    options: ["Create a new account","Wait 24 hours and try again","Call the billing department","Check their spam folder"],
    correct: 3,
    explanation: "「メールが見当たらない場合は迷惑メールフォルダを確認」とあるため(D)。(A)新規作成・(B)24時間待つ・(C)請求部門への電話は本文にない。",
    translation: "（ヘルプセンター：パスワードの再設定）パスワードを忘れた場合は、ログインページで「パスワードをお忘れですか」をクリックし、アカウントに登録したメールを入力してください。再設定リンクを送信します（30分で期限切れ）。メールが見当たらない場合は迷惑メールフォルダをご確認ください。さらにお困りの際はライブチャットでサポートへご連絡ください。",
    skill: "依頼内容把握",
    source: "オリジナル問題",
    verified: false
  }
];
