// TOEIC Reading Hub β — Part 6 Text Completion 問題データ
// 共通スキーマ:
// {
//   id: "TOEIC-2026-0001",
//   part: "Part 6 Text Completion",
//   level: "easy" | "medium" | "hard",
//   question: "空所を含む短文（または該当文）。空所は ____ で表す",
//   options: ["A", "B", "C", "D"],
//   correct: 0,            // 0〜3
//   explanation: "日本語の解説",
//   translation: "英文の和訳",
//   skill: "文脈語彙 / 接続表現 / 文選択 など",
//   source: "オリジナル問題",
//   verified: false
// }
// すべてオリジナル英文・オリジナル設問。公式問題・既存教材のコピー禁止。
const QUESTIONS_P6 = [
  {
    id: "TOEIC-2026-0005",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Thank you for your interest in our service. Unfortunately, the Basic plan you mentioned is no longer available. ____, we recommend the Standard plan, which includes all the same features at a similar price.",
    options: ["Instead", "Likewise", "Therefore", "For example"],
    correct: 0,
    explanation: "廃止されたプランの「代わりに」別のプランを勧める流れなので Instead が正解。(B) Likewise は「同様に」で前文と並列の内容を導く語なので文脈に合わず、(C) Therefore は因果関係、(D) For example は例示で文脈に合わない。",
    translation: "当サービスにご関心をお寄せいただきありがとうございます。あいにく、お問い合わせのベーシックプランは現在ご利用いただけません。代わりに、ほぼ同じ機能を同程度の価格で備えたスタンダードプランをお勧めします。",
    skill: "Part 6 接続副詞（文脈のつながり）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0006",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "We were disappointed with the recent shipment. Because the supplier failed to ____ the terms of the contract, we have decided to look for a new vendor.",
    options: ["honor", "admit", "remind", "consist"],
    correct: 0,
    explanation: "honor the terms of the contract で「契約条件を守る・履行する」という意味になり、新しい業者を探す理由として自然。(B) admit は「認める」、(C) remind は「思い出させる」、(D) consist は「成り立つ（consist of）」で文意に合わない。",
    translation: "最近の納品には失望させられた。供給業者が契約条件を守らなかったため、私たちは新しいベンダーを探すことにした。",
    skill: "Part 6 文脈語彙・コロケーション（honor the terms）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0037",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "To all staff,\n\nThe cafeteria will be closed this Friday for maintenance. ____, employees may use the second-floor meeting room as a temporary lunch area.\n\nThank you for your understanding.",
    options: ["In the meantime", "For example", "On the contrary", "Even so"],
    correct: 0,
    explanation: "カフェテリア閉鎖の「その間」に代替スペースを案内する流れなので In the meantime が正解。For example は例示、On the contrary は逆接、Even so は譲歩で文脈に合わない。",
    translation: "全スタッフへ。今週金曜、カフェテリアはメンテナンスのため閉鎖されます。その間、従業員は2階の会議室を臨時の昼食スペースとして利用できます。ご理解に感謝します。",
    skill: "Part 6 接続表現（In the meantime）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0038",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Thank you for applying for the marketing position. We received a large number of applications this year. ____, the review process may take longer than usual.\n\nWe appreciate your patience.",
    options: ["However", "Therefore", "Nevertheless", "Otherwise"],
    correct: 1,
    explanation: "応募が多い→だから審査に時間がかかる、という因果関係なので Therefore が正解。However と Nevertheless は逆接、Otherwise は「さもないと」で文脈に合わない。",
    translation: "マーケティング職へのご応募ありがとうございます。今年は多数の応募がありました。そのため、選考には通常より時間がかかる場合があります。お待ちいただけますと幸いです。",
    skill: "Part 6 接続表現（Therefore 因果）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0039",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "Demand for our handmade furniture has grown steadily over the past few years. ____, we have decided to open a second workshop to keep up with orders.\n\nWe thank our loyal customers for their continued support.",
    options: ["Otherwise", "Meanwhile", "As a result", "In contrast"],
    correct: 2,
    explanation: "需要の増加→その結果として工房を増やす、という因果なので As a result が正解。Otherwise は「さもないと」、Meanwhile は「その間」、In contrast は「対照的に」で文脈に合わない。",
    translation: "当店の手作り家具の需要は、過去数年で着実に伸びてきました。その結果、注文に対応するため2つ目の工房を開くことにしました。ご愛顧くださるお客様に感謝します。",
    skill: "Part 6 接続表現（As a result）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0040",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "The software update will be installed automatically tonight. Most users will not notice any change. ____, a few advanced features may look slightly different the next morning.",
    options: ["Likewise", "For instance", "Therefore", "However"],
    correct: 3,
    explanation: "「ほとんど変化なし」に対し「一部の機能は見た目が変わる」という逆接なので However が正解。Likewise は「同様に」、For instance は「例えば」、Therefore は「だから」で文脈に合わない。",
    translation: "ソフトウェアの更新は今夜自動的にインストールされます。ほとんどのユーザーは変化に気づかないでしょう。しかし、一部の高度な機能は翌朝、見た目が少し異なるかもしれません。",
    skill: "Part 6 接続表現（However 逆接）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0041",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "We are pleased to ____ that Ms. Reyes has been promoted to regional director. She will begin her new role on August 1.\n\nPlease join us in congratulating her.",
    options: ["require", "announce", "remind", "apologize"],
    correct: 1,
    explanation: "昇進を「発表・お知らせする」の意味になる announce が正解。require は「要求する」、remind は「思い出させる」、apologize は「謝る」で文脈に合わない。",
    translation: "レイエスさんが地域ディレクターに昇進したことをお知らせいたします。彼女は8月1日に新しい職務を開始します。一緒にお祝いしましょう。",
    skill: "Part 6 文脈動詞（announce）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0042",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Before using the laboratory equipment, all interns must complete a short safety ____. The session takes about thirty minutes and is held every Monday morning.",
    options: ["receipt", "refund", "training", "vacancy"],
    correct: 2,
    explanation: "安全に関する「研修・トレーニング」training が正解。後続の「session（講習）」とも自然につながる。receipt は「領収書」、refund は「返金」、vacancy は「欠員」で文脈に合わない。",
    translation: "実験器具を使用する前に、すべてのインターンは短い安全研修を受けなければなりません。その講習は約30分で、毎週月曜の朝に行われます。",
    skill: "Part 6 文脈名詞（training）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0043",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "Due to the upcoming system upgrade, online banking will be temporarily suspended this weekend. We recommend that customers ____ any urgent transactions before Friday evening.",
    options: ["postpone", "cancel", "ignore", "complete"],
    correct: 3,
    explanation: "一時停止の前に緊急の取引を「完了させる」complete が正解。postpone は「延期する」、cancel は「取り消す」、ignore は「無視する」で、停止前に済ませるという助言の文脈に合わない。",
    translation: "今後のシステムアップグレードのため、オンラインバンキングは今週末、一時的に停止されます。お客様は緊急のお取引を金曜の夕方までに完了させることをお勧めします。",
    skill: "Part 6 文脈動詞（complete）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0044",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Attached is the updated ____ for next week's training sessions. Please note that the Tuesday workshop has been moved to 2 p.m.",
    options: ["schedule", "warranty", "receipt", "salary"],
    correct: 0,
    explanation: "研修の「予定表・スケジュール」schedule が正解。後続で時間変更に触れている点とも合う。warranty は「保証書」、receipt は「領収書」、salary は「給与」で文脈に合わない。",
    translation: "来週の研修セッションの更新済みスケジュールを添付します。火曜のワークショップが午後2時に変更された点にご注意ください。",
    skill: "Part 6 文脈名詞（schedule）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0045",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "We have received your inquiry about the delayed shipment. ____ has been forwarded to our logistics team, who will contact you within 24 hours.",
    options: ["They", "These", "It", "Those"],
    correct: 2,
    explanation: "単数の your inquiry を指すので単数代名詞 It が正解。They・These・Those はいずれも複数を指し、先行する単数名詞と一致しない。",
    translation: "配送遅延に関するお問い合わせを受け取りました。それは物流チームに転送され、24時間以内にご連絡いたします。",
    skill: "Part 6 代名詞（単数 It の一致）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0046",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "Our records show that your membership ____ on June 30. To continue enjoying member benefits, please renew before that date.",
    options: ["expired", "has expired", "had expired", "will expire"],
    correct: 3,
    explanation: "6月30日という未来の期日に失効するので未来形 will expire が正解。expired・has expired・had expired は過去や完了で、これから更新を促す文脈に合わない。",
    translation: "記録によると、お客様の会員資格は6月30日に失効します。会員特典を継続してご利用いただくため、その日までに更新してください。",
    skill: "Part 6 時制（未来 will expire）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0047",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "The company will switch to a four-day workweek starting next month. ____ change is intended to improve employee well-being and overall productivity.",
    options: ["This", "Their", "Whose", "What"],
    correct: 0,
    explanation: "前文の内容（週4日制への移行）を受けて「この変更」とするので指示形容詞 This が正解。Their・Whose・What はここで change を自然に修飾できない。",
    translation: "当社は来月から週4日制に移行します。この変更は、従業員の幸福と全体的な生産性を向上させることを目的としています。",
    skill: "Part 6 指示語（This + 名詞）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0048",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "Thank you for visiting our booth at the trade fair last week. Since then, we ____ a number of requests for product samples, and we are processing them in order.",
    options: ["receive", "have received", "had received", "will receive"],
    correct: 1,
    explanation: "Since then（それ以来）現在までに受け取った状況なので現在完了 have received が正解。receive は現在形、had received は過去完了、will receive は未来で時制が合わない。",
    translation: "先週の見本市で当社のブースにお越しいただきありがとうございました。それ以来、製品サンプルのご依頼を多数いただいており、順番に対応しています。",
    skill: "Part 6 時制（現在完了 since then）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0049",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "If you wish to take annual leave next month, please ____ a request through the online portal at least two weeks in advance.",
    options: ["take", "bring", "give", "submit"],
    correct: 3,
    explanation: "submit a request で「申請を提出する」という定型表現になるので submit が正解。take・bring・give は request と自然に結びつかない。",
    translation: "来月年次休暇を取りたい場合は、少なくとも2週間前にオンラインポータルから申請を提出してください。",
    skill: "Part 6 コロケーション（submit a request）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0050",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "All applicants must ____ the minimum requirements listed in the job description before submitting their resumes.",
    options: ["meet", "arrive", "join", "agree"],
    correct: 0,
    explanation: "meet the requirements で「要件を満たす」という定型表現になるので meet が正解。arrive・join・agree は requirements を目的語に取れない。",
    translation: "すべての応募者は、履歴書を提出する前に、職務記述書に記載された最低要件を満たさなければなりません。",
    skill: "Part 6 コロケーション（meet requirements）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0051",
    part: "Part 6 Text Completion",
    level: "hard",
    question: "The renovation project is currently behind schedule. To ____ for the delay, the contractor has agreed to add an extra crew next week.",
    options: ["catch up", "make up", "keep up", "take up"],
    correct: 1,
    explanation: "make up for で「（遅れなどを）埋め合わせる」という句動詞になるので make up が正解。catch up は「追いつく」、keep up は「維持する」、take up は「取り上げる」で、for と結びついてこの意味にはならない。",
    translation: "改装プロジェクトは現在、予定より遅れています。その遅れを埋め合わせるため、請負業者は来週、追加の作業班を投入することに同意しました。",
    skill: "Part 6 句動詞（make up for）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0052",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Dear valued customer,\n\nThank you for your recent purchase from our online store. ____ If you have any concerns about your order, our support team is available 24 hours a day.\n\nBest regards,\nCustomer Care",
    options: ["We are sorry to hear that you wish to cancel your account.", "Please find the attached invoice for your monthly subscription.", "We hope you are completely satisfied with your purchase.", "Your application has been added to our waiting list."],
    correct: 2,
    explanation: "購入のお礼に続き、問い合わせ窓口の案内へ自然につなぐのは「ご購入にご満足いただけていれば幸いです」という(C)。(A) 解約、(B) 請求書、(D) 順番待ちは購入後のお礼の文脈に合わない。",
    translation: "いつもご利用のお客様へ。先日は当オンラインストアでお買い上げいただきありがとうございます。ご購入にご満足いただけていれば幸いです。ご注文についてご不明な点があれば、サポートチームが24時間対応しています。敬具／カスタマーケア",
    skill: "Part 6 文挿入（流れに合う一文）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0053",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "Notice to all residents:\n\nThe building's water supply will be shut off on Saturday from 9 a.m. to 1 p.m. for pipe repairs. ____ We apologize for any inconvenience this may cause.",
    options: ["The elevator will also be repainted next month.", "Parking permits must be renewed by the end of the year.", "The fitness center has extended its opening hours.", "We recommend storing enough water for the morning beforehand."],
    correct: 3,
    explanation: "断水の告知に続き、最も自然なのは「午前中に必要な水を事前にためておくことを勧める」(D)。(A) 塗装、(B) 駐車許可、(C) ジムの時間延長はいずれも断水の話題と無関係。",
    translation: "居住者の皆様へ。土曜の午前9時から午後1時まで、配管修理のため建物の給水を停止します。午前中に必要な水を事前にためておくことをお勧めします。ご不便をおかけし申し訳ありません。",
    skill: "Part 6 文挿入（文脈に沿う助言）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0054",
    part: "Part 6 Text Completion",
    level: "hard",
    question: "From: Conference Organizing Team\n\nThank you for registering for the annual technology summit. ____ Once we confirm the final number of attendees, we will send you the venue details and the full program.\n\nWe look forward to seeing you there.",
    options: ["Your registration has been received and is currently being processed.", "Unfortunately, the event has been canceled due to low interest.", "Please submit your final payment after the conference ends.", "The keynote speaker has decided to withdraw from the event."],
    correct: 0,
    explanation: "登録のお礼の後、「登録を受け付け、現在処理中」とし、後続の『人数確定後に詳細を送る』へ自然につながる(A)が正解。(B) 中止、(C) 会議後の支払い、(D) 講演者の辞退は、前向きに案内を続ける流れと矛盾する。",
    translation: "件名：会議運営チームより。年次技術サミットにご登録いただきありがとうございます。ご登録を受け付け、現在処理を進めています。参加人数が確定し次第、会場の詳細と全プログラムをお送りします。お会いできるのを楽しみにしています。",
    skill: "Part 6 文挿入（前後の流れ判断）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0121",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Thank you for your continued support. Our store will be expanding its opening hours starting next week. ____, we will introduce a new self-checkout system to reduce waiting times.",
    options: ["Otherwise","In contrast","Furthermore","For example"],
    correct: 2,
    explanation: "営業時間延長に加えて新システム導入という追加情報なので Furthermore が正解。(A) Otherwise「さもないと」、(B) In contrast「対照的に」、(D) For example「例えば」は文脈に合わない。",
    translation: "日頃のご愛顧ありがとうございます。当店は来週から営業時間を延長します。さらに、待ち時間を減らすため新しいセルフレジを導入します。",
    skill: "Part 6 接続表現（Furthermore 追加）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0122",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Dear Passenger,\n\nThank you for booking with us. If there are any changes to your flight schedule, the airline will ____ you by email or text message. Please make sure your contact details are up to date in your account.",
    options: ["notify","decline","purchase","expire"],
    correct: 0,
    explanation: "変更を「（人に）知らせる」notify が正解。(B) decline「断る」、(C) purchase「購入する」、(D) expire「失効する」は文意に合わない。",
    translation: "（航空会社メール）ご予約ありがとうございます。便のスケジュールに変更があれば、航空会社はメールかショートメッセージでお知らせします。アカウントの連絡先が最新であることをご確認ください。",
    skill: "Part 6 文脈動詞（notify）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0123",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Thank you for shopping with us. We want you to be completely satisfied with your order. If the item you received is damaged, please contact us within seven days and we will send a ____ at no extra charge.",
    options: ["complaint","replacement","discount","deposit"],
    correct: 1,
    explanation: "破損品に対し「交換品」を送る文脈なので replacement が正解。(A) complaint「苦情」、(C) discount「割引」、(D) deposit「保証金」は文意に合わない。",
    translation: "（店舗メール）当店でのお買い物ありがとうございます。ご注文に十分ご満足いただきたいと考えています。お受け取りの商品が破損していた場合は、7日以内にご連絡ください。追加料金なしで交換品をお送りします。",
    skill: "Part 6 文脈名詞（replacement）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0124",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "Dear Applicant,\n\nThank you for your interest in our program. We are writing to inform you that your application ____ and is now under review by our admissions team. We will contact you with a decision within two weeks.",
    options: ["receives","is receiving","will receive","has been received"],
    correct: 3,
    explanation: "申請書は「受領された」側で、現在までに完了した状況なので現在完了の受動 has been received が正解。(A) 現在能動・(B) 現在進行・(C) 未来は時制・態が合わない。",
    translation: "（入学事務局メール）出願者の皆様へ。当プログラムにご関心をお寄せいただきありがとうございます。お客様の出願書類を受領し、現在、入学審査チームが審査中であることをお知らせします。2週間以内に結果をご連絡します。",
    skill: "Part 6 時制（現在完了の受動）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0125",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "To our valued visitors,\n\nSome visitors recently reported difficulty finding the main entrance. To address ____ concerns, we have installed clearer signs throughout the building. We hope this makes your next visit easier.",
    options: ["such","another","either","much"],
    correct: 0,
    explanation: "前文の内容（入口が分かりにくいという報告）を受けて「そうした懸念」とするので such が正解。(B) another「別の」、(C) either「どちらかの」、(D) much は可算名詞 concerns を修飾できず文意に合わない。",
    translation: "（来館者向けお知らせ）ご来館の皆様へ。最近、正面入口が見つけにくいとの声が一部の来館者から寄せられました。そうした懸念に対応するため、館内各所により分かりやすい標識を設置しました。次回のご来館がより快適になることを願っています。",
    skill: "Part 6 指示語（such + 名詞）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0126",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Spaces for our monthly workshop are limited and tend to fill up quickly. To guarantee a seat at the workshop, participants are advised to register at least three days ____. Registrations cannot be accepted once the class is full.",
    options: ["by then","on time","in advance","at once"],
    correct: 2,
    explanation: "「前もって・事前に」を表す in advance が正解。(A) by then「その時までに」、(B) on time「時間どおりに」、(D) at once「すぐに」は文意に合わない。",
    translation: "（ワークショップ案内）月例ワークショップの席には限りがあり、すぐに埋まる傾向があります。席を確保するため、参加者は少なくとも3日前までに登録するよう勧められています。定員に達すると登録は受け付けられません。",
    skill: "Part 6 コロケーション（in advance）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0127",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "The training day is divided into two parts. The morning session will focus on basic skills, ____ the afternoon session will cover advanced techniques. A break for lunch will be provided between the two sessions.",
    options: ["while","unless","because","despite"],
    correct: 0,
    explanation: "午前と午後の内容を対比する「一方で」の意味で while が正解。(B) unless「〜でない限り」、(C) because「〜なので」、(D) despite は前置詞で後ろに節を取れず、いずれも文意に合わない。",
    translation: "（研修案内）研修日は2部構成です。午前のセッションは基礎スキルに焦点を当て、一方で午後のセッションは応用テクニックを扱います。2つのセッションの間には昼食休憩が設けられます。",
    skill: "Part 6 接続詞（対比の while）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0128",
    part: "Part 6 Text Completion",
    level: "hard",
    question: "Dear Mr. Hayes,\n\nThank you for your interest in joining our book club. ____ Meetings are held on the first Saturday of each month at the community library. We look forward to seeing you there.",
    options: ["Unfortunately, the club is no longer accepting new members.","Please return the damaged book to the front desk.","Your monthly subscription fee is now overdue.","We are pleased to confirm that your membership is now active."],
    correct: 3,
    explanation: "入会への関心へのお礼に続き、会の開催案内へ自然につながるのは「入会が有効になった」と確認する(D)。(A)募集終了・(B)破損本の返却・(C)会費延滞は歓迎して案内を続ける流れと矛盾する。",
    translation: "ヘイズ様。当ブッククラブへのご関心ありがとうございます。ご入会が有効になりましたことをお知らせします。例会は毎月第1土曜日にコミュニティ図書館で開催します。お会いできるのを楽しみにしています。",
    skill: "Part 6 文挿入（流れに合う一文）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0129",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Dear Library Member,\n\nThis is a friendly reminder that your library books are ____ on Friday. Please return or renew them to avoid late fees. You can renew your items online or at the front desk.",
    options: ["spent","due","paid","kept"],
    correct: 1,
    explanation: "「（返却などの）期限が来ている」を表す due が正解。(A) spent「費やされた」、(C) paid「支払われた」、(D) kept「保たれた」は文意に合わない。",
    translation: "（図書館リマインダー）会員の皆様へ。図書館の本の返却期限が金曜であることをお知らせします。延滞料金を避けるため、返却または貸出延長をお願いします。オンラインまたは受付で貸出延長ができます。",
    skill: "Part 6 文脈語彙（due 期限）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0130",
    part: "Part 6 Text Completion",
    level: "hard",
    question: "Notice to all employees:\n\nThe parking garage will undergo cleaning this Saturday. ____ Please remove your vehicle by 7 a.m. to avoid any inconvenience.",
    options: ["The new cafeteria menu will be available next week.","All employees must complete the annual survey by Friday.","No vehicles will be allowed inside between 8 a.m. and 4 p.m.","The company picnic has been rescheduled to next month."],
    correct: 2,
    explanation: "清掃の告知と「7時までに車を移動」という指示の間に最も自然なのは、車両の進入禁止時間を伝える(C)。(A)カフェメニュー・(B)アンケート・(D)ピクニックは駐車場清掃の話題と無関係。",
    translation: "全従業員へのお知らせ。今週土曜、立体駐車場の清掃を行います。午前8時から午後4時の間は車両の進入を禁止します。ご不便を避けるため午前7時までに車を移動してください。",
    skill: "Part 6 文挿入（文脈に沿う情報）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0181",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Our flagship store will be closed for renovation from May 1 to May 7. ____, customers can continue to place orders through our website and mobile app.",
    options: ["However", "Therefore", "For instance", "As a result"],
    correct: 0,
    explanation: "店舗は閉まるが、オンラインでは注文を続けられるという対比なので However が正解。(B) Therefore・(D) As a result は因果、(C) For instance は例示で文脈に合わない。",
    translation: "当社の旗艦店は5月1日から7日まで改装のため閉店します。しかし、お客様はウェブサイトやモバイルアプリから引き続きご注文いただけます。",
    skill: "Part 6 接続副詞（However 対比）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0182",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Thank you for submitting your application. Our hiring team will review it and contact you ____ to arrange an interview.",
    options: ["short", "shortly", "shorter", "shortness"],
    correct: 1,
    explanation: "動詞 contact を修飾し「まもなく」を表す副詞 shortly が正解。(A) short はこの意味では使わず、(C) shorter は比較級、(D) shortness は名詞で不適。",
    translation: "ご応募ありがとうございます。採用チームが内容を確認し、面接を設定するためまもなくご連絡します。",
    skill: "Part 6 語形（副詞 shortly）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0183",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "We are excited to announce that our second location ____ in the downtown district early next year.",
    options: ["open", "will open", "has opened", "opened"],
    correct: 1,
    explanation: "early next year という未来の時を示す語句があるため、未来を表す will open が正解。(A) open は主語 our second location（三人称単数）に対する述語動詞として時制・一致が合わず、(C) has opened・(D) opened は過去・完了で未来の予定に合わない。",
    translation: "来年初め、当社の2号店が中心街にオープンすることをお知らせできて光栄です。",
    skill: "Part 6 時制（未来 will）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0184",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Please be aware that the standard warranty does not ____ damage resulting from accidental drops or misuse.",
    options: ["cover", "contain", "concern", "consist"],
    correct: 0,
    explanation: "保証が損傷を「対象に含む・補償する」を表す cover が正解。(B) contain「（中身を）含む」、(C) concern「関係する」、(D) consist「成り立つ」は文意に合わない。",
    translation: "標準保証は、誤って落としたり誤用したりして生じた損傷は補償しないことにご注意ください。",
    skill: "Part 6 文脈語彙（cover 補償する）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0185",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "The agenda for Thursday's meeting has been revised. ____ The updated version is attached to this email for your reference.",
    options: ["Two new items have been added to the discussion list.", "The cafeteria will introduce a new menu next week.", "Parking permits must be renewed by the end of the month.", "The company picnic was a great success this year."],
    correct: 0,
    explanation: "前後が「議題が改訂された」「更新版を添付」という内容なので、改訂の具体を述べる(A)が文脈に合う。(B)(C)(D)は議題の改訂と無関係。",
    translation: "木曜の会議の議題が改訂されました。討議リストに新たに2項目が追加されました。最新版を参考までにこのメールに添付します。",
    skill: "Part 6 文選択（文脈に合う一文）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0186",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "The main supplier raised its prices by fifteen percent last month. ____, the company has begun evaluating several alternative vendors.",
    options: ["As a result", "Otherwise", "Likewise", "Nevertheless"],
    correct: 0,
    explanation: "値上げを原因として代替業者の検討を始めた、という因果なので As a result が正解。(B) Otherwise「さもなければ」、(C) Likewise「同様に」、(D) Nevertheless「それでも」は文脈に合わない。",
    translation: "主要な供給業者が先月15パーセント値上げした。その結果、会社はいくつかの代替業者の評価を始めた。",
    skill: "Part 6 接続表現（As a result 因果）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0187",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "Employees who wish to update ____ benefits selections must complete the form before the enrollment period ends.",
    options: ["its", "their", "theirs", "them"],
    correct: 1,
    explanation: "複数の先行詞 Employees を受け、後ろの名詞 selections を修飾する所有格 their が正解。(A) its は単数、(C) theirs は所有代名詞で名詞を続けられず、(D) them は目的格。",
    translation: "福利厚生の選択内容を更新したい従業員は、登録期間が終わる前にフォームを記入しなければならない。",
    skill: "Part 6 代名詞（所有格 their）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0188",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "The user guide clearly explains how to ____ the bookshelf using only the included tools.",
    options: ["assemble", "assume", "assign", "assist"],
    correct: 0,
    explanation: "部品を組み合わせて家具を「組み立てる」を表す assemble が正解。(B) assume「思い込む」、(C) assign「割り当てる」、(D) assist「手伝う」は文意に合わない。",
    translation: "その取扱説明書は、付属の工具だけを使って本棚を組み立てる方法を分かりやすく説明している。",
    skill: "Part 6 文脈語彙（assemble）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0189",
    part: "Part 6 Text Completion",
    level: "advanced",
    question: "Thank you for your recent purchase from our online store. ____ If for any reason you are not satisfied, you may return the item within 30 days for a full refund.",
    options: ["We hope the product meets all of your expectations.", "Our warehouse will be relocating next spring.", "Job openings are listed on our careers page.", "Shipping rates increased earlier this year."],
    correct: 0,
    explanation: "購入の御礼に続き、返品案内へとつながる流れなので、満足を願う(A)が自然。(B)(C)(D)は購入・返品の文脈と無関係。",
    translation: "このたびは当オンラインストアでのご購入ありがとうございます。製品がご期待に沿うことを願っております。万一ご満足いただけない場合は、30日以内に返品いただければ全額返金します。",
    skill: "Part 6 文選択（文脈に合う一文）",
    source: "オリジナル問題",
    verified: false
  },
  {
    id: "TOEIC-2026-0190",
    part: "Part 6 Text Completion",
    level: "standard",
    question: "The premium membership comes with a range of benefits, ____ free express shipping, early access to sales, and exclusive discounts.",
    options: ["such as", "in case", "rather than", "so that"],
    correct: 0,
    explanation: "後ろに具体例が並ぶため「〜のような」を表す such as が正解。(B) in case「〜の場合に備えて」、(C) rather than「〜よりむしろ」、(D) so that「〜するように」は例示の文脈に合わない。",
    translation: "プレミアム会員には、送料無料の速達、セールへの先行アクセス、限定割引など、さまざまな特典が付いている。",
    skill: "Part 6 接続表現（such as 例示）",
    source: "オリジナル問題",
    verified: false
  }
];
